#!/usr/bin/env bash
# This bash script pings 5 times an IP address passed as an argument.
# It Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument is passed

ip=$1
if [ -z "$ip" ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$ip"
fi
